services:
  mariadb:
    image: mariadb:11.4
    container_name: syrabet-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: syrabet
      MARIADB_USER: syrabet
      MARIADB_PASSWORD: syrabet
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d

volumes:
  mariadb_data:
